# Generated by Django 2.0.6 on 2018-06-04 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Gossip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gossip_text', models.CharField(max_length=2048)),
                ('create_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField(null=True)),
                ('is_enabled', models.BooleanField()),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gossips.Character')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
